### ISSUE TITLE
Timezone still required

### ISSUE THREAD

**Issue by Didgeridrew** [allenporter/hass-local-calendar#10]
version: 0.0.2  latest update
ical 4.1.1

The times are incorrect if timezone is not specified.  Times are not defaulting to local.

This service call:
```
service: local_calendar.create_event
data:
  summary: Testing 16:30-17:00 No TZ
  description: ""
  dtstart: "2022-11-18T16:30:00"
  dtend: "2022-11-18T17:00:00"
target:
  entity_id: calendar.drew
```
Yields the following:
```
message: Testing 16:30-17:00 No TZ
all_day: false
start_time: '2022-11-18 11:30:00'
end_time: '2022-11-18 12:00:00'
location: ''
description: ''
friendly_name: Drew
```

Date-only/all-day events are also off.

Times should be localized automatically or services example fields should indicate that timezones are required.
