### ISSUE TITLE
Failed to call service local_calendar.create_event

### ISSUE THREAD

**Issue by MrThiemann** [allenporter/hass-local-calendar#5]
very nice!
we were still talking about it today in Discord because someone was looking for a local calendar.
So I did a search and found this one! Perfect!!
However I have the problem that I cannot add an entry via the call service.
Maybe you know how to fix it?

`Failed to call service local_calendar.create_event. extra keys not allowed @ data['end_date']. Got None extra keys not allowed @ data['start_date']. Got None required key not provided @ data['dtend']. Got None required key not provided @ data['dtstart']. Got None`

**Comment by allenporter** [comment]
I think my example is wrong in `info.md` and needs to be updated following the new fields in the table.

**Comment by MrThiemann** [comment]
I saw that you have already adjusted the info.md ? Or is that misleading?

Unfortunately, I still can't add an entry.
The error message remains the same

```
service: local_calendar.create_event
data:
  summary: Nightly
  rrule: FREQ=DAILY
  start_date_time: "2022-10-02T20:00:00"
  end_date_time: "2022-10-02T22:00:00"
target:
  entity_id: calendar.localkalender
```

![Bildschirmfoto 2022-10-04 um 16 26 25](https://user-images.githubusercontent.com/54147030/193845974-a0c5f34e-b7ee-4fe2-9f19-f3c6024a18c3.png)



_Fehler beim Aufrufen des Diensts local_calendar.create_event. extra keys not allowed @ data['end_date_time']. Got None extra keys not allowed @ data['start_date_time']. Got None required key not provided @ data['dtend']. Got None required key not provided @ data['dtstart']. Got None_

to be on the safe side, I also reloaded the HACS integration and the integration in HA once.

I haven't taken any other steps yet. Is anything missing here?

So once about my process:
I added your git as a custom repository in HACS.
Then searched for your "Local Calendar" and installed it.
A "Settings" --> "Integration", then searched for and configured the Local Calendar again
(a popup opens where I can name my calendar)
... that's pretty much all I did.


---

i saw your video from your calendar on discord... 
you even have a button in the calendar overview. Even I miss that?!

**Comment by allenporter** [comment]
I'm saying look at the table which is correct. It says `dtstart` instead of `start_date_time`

**Comment by allenporter** [comment]
I've updated the example now as well -- let's see if that works for you.

By the way, I plan to integrate this into home assistant core so just want to mention that these APIs may change once introduced there -- but consider this an early preview.

**Comment by MrThiemann** [comment]
This works for me: 

```
service: local_calendar.create_event
data:
   summary: "First"
   description: "Calendar entry works perfectly!"
   dtstart: "2022-10-05 20:00:00"
   dtend: "2022-10-05 23:00:00"
target:
  entity_id: calendar.automation
```
